config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

  concern :votable do
    member do
      patch :vote_for
      patch :vote_against
      delete :cancel_vote
    end
  end

  resources :questions, concerns: [ :votable ], except: :edit do
    resources :comments, only: :create
    resources :subscriptions, only: [ :create, :destroy ]
    resources :answers, concerns: [ :votable ], only: %i[show create update destroy] do
      resources :comments, only: :create

      member do
        patch :best
      end
    end
  end

  resources :awards, only: :index
  resources :files, only: :destroy
  resources :links, only: :destroy

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
require 'concerns/votable'
require 'concerns/commentable'

class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :user
  has_one :award, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :votes, dependent: :destroy, as: :votable
  has_many :subscriptions, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :award, reject_if: :all_blank

  has_many_attached :files

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :subscribe_author

  scope :last_day, -> { where(created_at: 1.day.ago..Time.now) }

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_author
    user.subscriptions.create(question_id: id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: [:show, :update, :destroy]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question, serializer: QuestionSerializer
    else
      render json: { errors: @question.errors.full_messages }
    end
  end

  def update
    if @question.update(question_params)
      render json: @question, serializer: QuestionSerializer
    else
      render json: { errors: @question.errors.full_messages }
    end
  end

  def destroy
    @question.destroy!
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: [:name, :url], award_attributes: [:title, :image])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  after_action :publish_question, only: :create

  authorize_resource

  include Voted

  def index
    @questions = Question.all
  end

  def show
    answer.links.build
  end

  def new
    question.links.build
    question.build_award
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if current_user.author_of?(question)
      question.update(question_params)
    else
      render status: :forbidden
    end
  end

  def destroy
    question.destroy if current_user.author_of?(question)
    redirect_to questions_path
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  def answer
    @answer ||= question.answers.new
  end

  def comment
    @comment ||= question.comments.new
  end

  helper_method :question
  helper_method :comment
  helper_method :answer

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: [:name, :url], files: [], award_attributes: [:title, :image])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      question: render_question
    )
  end

  def render_question
    QuestionsController.renderer.instance_variable_set(
      :@env, {
      "HTTP_HOST" => "localhost:3000",
      "HTTPS" => "off",
      "REQUEST_METHOD" => "GET",
      "SCRIPT_NAME" => '',
      "warden" => warden
      }
    )

    QuestionsController.render(
      partial: 'questions/question_preview',
      locals: { question: @question }
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_award_fields.html.slim
p
  = f.label :title, 'Award title'
  = f.text_field :title
p
  = f.label :image, 'Award image'
  = f.file_field :image, direct_upload: true

app/views/questions/_question.html.slim
div id = "question-#{question.id}"
  p.question__user-email = "#{question.user.email} asks"

  h1.question__title = question.title
  p.question__body = question.body

  - if can?(:create, Subscription) && !question_subscription(question)
    = link_to 'Subscribe', question_subscriptions_path(question), method: :post, remote: true
  - if can?(:destroy, question_subscription(question)) && question_subscription(question)
    = link_to 'Unsubscribe', question_subscription_path(question, question_subscription(question)), method: :delete, remote: true

  .link-errors
  .links
    - if question.links.present?
      .links__title Links:
      ul
        - question.links.each do |l|
          li id="link-#{l.id}" class="links__item"
            - if gist?(l.url)
              script src="#{l.url}.js"
            = link_to l.name, l.url
            - if can?(:destroy, l)
              p = link_to 'Delete link', link_path(l), method: :delete, remote: true, class: 'links__delete'

  .files
    - if question.files.present?
      .files__title Files:
      = render partial: 'shared/file', collection: question.files

  .question-errors

  - if can?(:update, question)
    = link_to 'Edit', '#', data: { question_id: question.id }, class: 'edit-question-link'
    = form_with model: question, local: false, html: { id: "edit-question-#{question.id}" }, class: 'hidden' do |f|
      p = f.label :title
      = f.text_field :title
      p = f.label :body, 'Your question'
      = f.text_area :body
      p = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
      p = f.fields_for :links do |l|
        = render partial: 'shared/link_fields', locals: { f: l }
      .add-links
        = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
      p = f.submit 'Save'

  section.award
    - unless question.award.nil?
      h4 Award for the best answer
      = image_tag url_for(question.award.image), class: 'award__image'
      p.award__title = question.award.title

  - if user_signed_in?
    = render partial: 'shared/votes', locals: { model: question, polymorphic_model: question }

    .comments id="question-#{question.id}"
      = render question.comments
    .comment_form data-type="question" data-id="#{question.id}"
      = form_with model: [question, comment], local: false do |f|
        = f.label :body, 'Your comment'
        = f.text_area :body
        = f.submit 'Save'

app/views/questions/_question_preview.html.slim
h3 = question.title
p = question.body
p = link_to 'Show question', question_path(question)
- if can?(:destroy, question)
  p = link_to 'Delete question', question_path(question), method: :delete

app/views/questions/index.html.slim
- if user_signed_in?
  p = link_to 'Log out', destroy_user_session_path, method: :delete
  |
  p = link_to 'Your awards', awards_path
- else
  p = link_to 'Log in', new_user_session_path

.questions
  - @questions.each do |question|
    = render partial: 'questions/question_preview', locals: { question: question }

- if can?(:create, Question)
  p = link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question, local: true do |f|
  p = f.label :title
  = f.text_field :title
  p = f.label :body
  = f.text_area :body
  p = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  p = f.fields_for :links do |l|
    = render partial: 'shared/link_fields', locals: { f: l }
  .add-links
    = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
  p Award:
  p = f.fields_for :award do |a|
    = render partial: 'award_fields', locals: { f: a }
  p = f.submit 'Ask'

p = link_to 'All questions', questions_path

app/views/questions/show.html.slim
.wrapper
  - if user_signed_in?
    = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'button button_bordered'
    |
    = link_to 'Your awards', awards_path, class: 'button button_color-bordered'
  - else
    = link_to 'Log in', new_user_session_path, class: 'button button_bordered'

  .question data-id="#{question.id}"
    = render question

  h2 = 'Answers'
  ul.answers
    - if question.answers.best.present?
      = render question.answers.best
    = render question.answers.where(best: false)

  h2 = 'Answer the question'

  .answer-errors

  = form_with model: [question, answer], local: false, class: 'new-answer' do |f|
    p = f.label :body, 'Answer body'
    = f.text_area :body
    p = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
    p Links:
    p = f.fields_for :links do |l|
      = render partial: 'shared/link_fields', locals: { f: l }
    .add-links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
    p = f.submit 'Answer'

  p = link_to 'All questions', questions_path

  = javascript_pack_tag 'answer'
  = javascript_pack_tag 'question'
  = javascript_pack_tag 'vote'
  = javascript_pack_tag 'comment'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: question %>');

<% if !question.errors.present? %>
  $("#question-<%= question.id %>").html('<%= j render question %>')
  $('form#edit-question-<%= question.id %>').hide();
  $('.edit-question-link').show();
<% end %>