config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        resources :answers, only: [:index, :show, :create, :update, :destroy]
      end
    end
  end

  concern :votable do
    member do
      patch :vote_for
      patch :vote_against
      delete :cancel_vote
    end
  end

  resources :questions, concerns: [ :votable ], except: :edit do
    resources :comments, only: :create
    resources :subscriptions, only: [ :create, :destroy ]
    resources :answers, concerns: [ :votable ], only: %i[show create update destroy] do
      resources :comments, only: :create

      member do
        patch :best
      end
    end
  end

  resources :awards, only: :index
  resources :files, only: :destroy
  resources :links, only: :destroy

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
require 'concerns/votable'
require 'concerns/commentable'

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :body, presence: true
  validate :validates_only_best_answer

  after_create :notify_subscribers

  def self.best
    where(best: true).first
  end

  def make_best
    previous_best_answer = question.answers.best

    Answer.transaction do
      if previous_best_answer.present?
        previous_best_answer.update!(best: false)
      end
      question.award&.reward_best(user)

      update!(best: true)
    end
  end

  private

  def validates_only_best_answer
    return unless best

    if question.answers.best.present?
      errors.add(:best, 'cannot have another best answer')
    end
  end

  def notify_subscribers
    AnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :authenticate_user!
  after_action :publish_answer, only: :create

  load_and_authorize_resource

  include Voted

  def create
    @answer = question.answers.new(answer_params.merge(user: current_user))
    @answer.save
  end

  def update
    answer.update(answer_params)
  end

  def destroy
    answer.destroy
  end

  def best
    authorize! :best, answer
    answer.make_best
  end

  private

  def answer
    @answer ||= params[:id] ? Answer.find(params[:id]) : Answer.new
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  def comment
    @comment = answer.comments.new
  end

  helper_method :answer
  helper_method :question
  helper_method :comment

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "question_#{@answer.question.id}",
      answer: render_answer
    )
  end

  def render_answer
    AnswersController.renderer.instance_variable_set(
      :@env, {
      "HTTP_HOST" => "localhost:3000",
      "HTTPS" => "off",
      "REQUEST_METHOD" => "GET",
      "SCRIPT_NAME" => '',
      "warden" => warden,
      "rack.input" => ''
    }
    )

    AnswersController.render(
      partial: 'answers/answer',
      locals: { answer: @answer, question: @answer.question }
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_answer, only: [:show, :update, :destroy]
  before_action :load_question, only: [:create]

  authorize_resource

  def index
    @answers = Answer.all
    render json: @answers, serializer_each: AnswersSerializer
  end

  def show
    render json: @answer, serializer: AnswersSerializer
  end

  def create
    @answer = current_resource_owner.answers.new(answer_params.merge(question: @question))

    if @answer.save
      render json: @answer, serializer: AnswersSerializer
    else
      render json: { errors: @answer.errors.full_messages }
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer, serializer: AnswersSerializer
    else
      render json: { errors: @answer.errors.full_messages }
    end
  end

  def destroy
    @answer.destroy!
  end

  private

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, links_attributes: [:name, :url])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
li id = "answer-#{answer.id}" class = 'answer'
  .answer-errors

  p.answer__user-email = answer.user.email + ' answers: '

  p.answer__body = answer.body

  .files
    - if answer.files.present?
      .files__title Files:
      = render partial: 'shared/file', collection: answer.files

  .link-errors
  .links
    - if answer.links.present?
      .links__title Links:
      ul
        - answer.links.each do |l|
          li id="link-#{l.id}" class="links__item"
            - if gist?(l.url)
              script src="#{l.url}.js"
            = link_to l.name, l.url
            - if can?(:destroy, l)
              p = link_to 'Delete link', link_path(l), method: :delete, remote: true, class: 'links__delete'

  - if answer.user.awards.include? question.award
    b AWARDED

  - if can?(:update, answer)
    p = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

  - if can?(:destroy, answer)
    p = link_to 'Delete answer', question_answer_path(question, answer), method: :delete, remote: true

  - if user_signed_in?
    = render partial: 'shared/votes', locals: { model: answer, polymorphic_model: [answer.question, answer] }

  - if can?(:best, answer)
    p = link_to 'Choose as best', best_question_answer_path(question, answer), method: :patch, remote: true

  .comments id="answer-#{answer.id}"
    = render answer.comments
  .comment_form data-type="answer" data-id="#{answer.id}"
    = form_with model: [question, answer, comment], local: false do |f|
      = f.label :body, 'Your comment'
      = f.text_area :body
      = f.submit 'Save'

  = form_with model: [answer.question, answer], local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    = f.label :body, 'Your answer'
    = f.text_area :body
    p = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
    p = f.fields_for :links do |l|
      = render partial: 'shared/link_fields', locals: { f: l }
    .add-links
      = link_to_add_association 'Add link', f, :links, partial: 'shared/link_fields'
    = f.submit 'Save'

app/views/answers/best.js.erb
<% if answer.persisted? %>
  $('#answer-<%= answer.id %>').remove();
  $('ul.answers').prepend('<%= j render answer %>');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% if answer.persisted? %>
  $('.answers').append('<%= j render answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= answer.id %>').remove();

app/views/answers/update.js.erb
$('#answer-<%= answer.id %> .answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% unless answer.errors.present? %>
  $('#answer-' + '<%= answer.id %>').html('<%= j render answer %>');
  $('#answer-' + '<%= answer.id %> .files').html('<%= j render partial: 'shared/file', collection: answer.files %>');
  $('form#edit-answer-' + '<%= answer.id %>').hide();
<% end %>